#!/bin/bash

# this has to be run as root, since port 80 is privileged

echo 'Starting the proxy server as root, only do this if you trust the software!';
sudo perl unlockserver.pl daemon -m production --listen 'http://*:80';
